---
title: "Maaslin16S_plots_alldepths"
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(tidyverse)
library(phyloseq)
library(dplyr)
library(readxl)
library(Hmisc)
```

Step 1: Pull out only the SF samples so that we can only look at those. 

```{r}
# otus <- read_csv("/Users/kyasparks/Desktop/16S_Maaslin_combined.csv")%>%
#   select(1,contains("_SF_"))

## this step is reading in my feature table, where 'feature' is my taxonomic string and 'OTU' is my ASV ID
# this is filtering my feature table to just contain 'SF' samples of all depths

otus <- read_excel("/Users/kyasparks/Desktop/Kya's Phd/CSU 2023-2024/Projects/ASCC/ASCC_July2024_USETHIS_ks/16S/16S_Maaslin/ASCC_16S_feature_table_Maaslin_combo.xlsx", sheet = "ALL")%>%
  select(3,contains("_SF_"))
```

```{r}
taxa <- read.delim("/Users/kyasparks/Desktop/Kya's Phd/CSU 2023-2024/Projects/ASCC/ASCC_July2024_USETHIS_ks/16S/16S_taxonomy/filtered/ASCC_16S_taxonomy_forprocessing_copy.txt")

full_table <- inner_join(taxa, otus, by = "OTUID")
full_table$ASV_FULL_tax <- apply(full_table[, 2:8], 1, paste, collapse = ";")


full_acido1 <- full_table %>% 
  pivot_longer(names_to = "samples", values_to = "counts", 9:88)%>% 
  group_by(samples, Phylum, OTUID, ASV_FULL_tax) %>% 
  summarise(sum = sum(counts))%>% 
  filter(sum>0) #%>%
  #pivot_wider(names_from = "samples", values_from = "sum")

most_common_asv <- full_acido1 %>%
  group_by(Phylum) %>%
  count(ASV_FULL_tax) %>%
  top_n(1, n) %>%
  ungroup()

full_acido1 <- full_acido1 %>%
  inner_join(most_common_asv, by = c("Phylum", "ASV_FULL_tax"))

# Pivot wider to get the counts for each sample and calculate occurrence
full_acido1_wide <- full_acido1 %>%
  pivot_wider(names_from = "samples", values_from = "sum")

full_acido1_wide$occurrence <- rowSums(full_acido1_wide[5:83] > 0, na.rm = TRUE)

full_acido_pres1 <- full_acido1_wide %>%
  pivot_longer(names_to = "samples", values_to = "rel_abund", 5:83) %>%
  mutate(Site = "SF")
```


```{r}
ggplot(full_acido_pres1, aes(y = ASV_FULL_tax, x= rel_abund, color = Site)) +
  stat_summary(fun.data = median_hilow, geom = "pointrange",
               fun.args = list(conf.int = .25),
               position = position_dodge(width = .5), size = .3) +
  scale_color_brewer(palette = "Set2") +
  labs(title = "Relative Abundance of Phyla by Site (SF Samples)",
       subtitle = "Median values with 50% confidence intervals",
       x = "Relative Abundance (%)", 
       y = "Phylum",
       color = "Taxonomic String") +
  theme(
    plot.title = element_text(size = 16, face = "bold", hjust = 0.5),
    plot.subtitle = element_text(size = 12, hjust = 0.5),
    axis.title.x = element_text(size = 12, face = "bold"),
    axis.title.y = element_text(size = 12, face = "bold"),
    axis.text.x = element_text(size = 10),
    axis.text.y = element_text(size = 10),
    legend.title = element_text(size = 12),
    legend.text = element_text(size = 10)
  )
```





Step 2: Pull out only the TP samples so that we can only look at those. 

```{r}
# otus <- read_csv("/Users/kyasparks/Desktop/16S_Maaslin_combined.csv")%>%
#   select(1,contains("_SF_"))

otus2 <- read_excel("/Users/kyasparks/Desktop/Kya's Phd/CSU 2023-2024/Projects/ASCC/ASCC_July2024_USETHIS_ks/16S/16S_Maaslin/ASCC_16S_feature_table_Maaslin_combo.xlsx", sheet = "ALL")%>%
  select(3,contains("_TP_"))
```

```{r}
taxa <- read.delim("/Users/kyasparks/Desktop/Kya's Phd/CSU 2023-2024/Projects/ASCC/ASCC_July2024_USETHIS_ks/16S/16S_taxonomy/filtered/ASCC_16S_taxonomy_forprocessing_copy.txt")



full_table2 <- inner_join(taxa, otus2, by = "OTUID")
full_table2$ASV_FULL_tax <- apply(full_table2[, 2:8], 1, paste, collapse = ";")


full_acido2 <- full_table2 %>% 
  pivot_longer(names_to = "samples", values_to = "counts", 9:94)%>% 
  group_by(samples, Phylum, OTUID, ASV_FULL_tax) %>% 
  summarise(sum = sum(counts))%>% 
  filter(sum>0) #%>%
  #pivot_wider(names_from = "samples", values_from = "sum")

most_common_asv <- full_acido2 %>%
  group_by(Phylum) %>%
  count(ASV_FULL_tax) %>%
  top_n(1, n) %>%
  ungroup()

full_acido2 <- full_acido2 %>%
  inner_join(most_common_asv, by = c("Phylum", "ASV_FULL_tax"))

# Pivot wider to get the counts for each sample and calculate occurrence
full_acido2_wide <- full_acido2 %>%
  pivot_wider(names_from = "samples", values_from = "sum")

full_acido2_wide$occurrence <- rowSums(full_acido2_wide[5:90] > 0, na.rm = TRUE)

full_acido_pres3 <- full_acido2_wide %>%
  pivot_longer(names_to = "samples", values_to = "rel_abund", 5:90) %>%
  mutate(Site = "TP")
```


```{r}

ggplot(full_acido_pres3, aes(y = ASV_FULL_tax, x= rel_abund, color = Site)) +
  stat_summary(fun.data = median_hilow, geom = "pointrange",
               fun.args = list(conf.int = .25),
               position = position_dodge(width = .5), size = .3) +
  scale_color_brewer(palette = "Set2") +
  labs(title = "Relative Abundance of Phyla by Site (TP Samples)",
       subtitle = "Median values with 50% confidence intervals",
       x = "Relative Abundance (%)", 
       y = "Phylum",
       color = "Taxonomic String") +
  theme(
    plot.title = element_text(size = 16, face = "bold", hjust = 0.5),
    plot.subtitle = element_text(size = 12, hjust = 0.5),
    axis.title.x = element_text(size = 12, face = "bold"),
    axis.title.y = element_text(size = 12, face = "bold"),
    axis.text.x = element_text(size = 10),
    axis.text.y = element_text(size = 10),
    legend.title = element_text(size = 12),
    legend.text = element_text(size = 10)
  )
```


```{r}
# otus3 <- read_csv("/Users/kyasparks/Desktop/16S_Maaslin_combined.csv")%>% 
#   select(1,contains("_SJ_"))

otus3 <- read_excel("/Users/kyasparks/Desktop/Kya's Phd/CSU 2023-2024/Projects/ASCC/ASCC_July2024_USETHIS_ks/16S/16S_Maaslin/ASCC_16S_feature_table_Maaslin_combo.xlsx", sheet = "ALL")%>%
  select(3,contains("_SJ_"))

```


```{r}
taxa <- read.delim("/Users/kyasparks/Desktop/Kya's Phd/CSU 2023-2024/Projects/ASCC/ASCC_July2024_USETHIS_ks/16S/16S_taxonomy/filtered/ASCC_16S_taxonomy_forprocessing_copy.txt")

full_table3 <- inner_join(taxa, otus3, by = "OTUID")

full_table3$ASV_FULL_tax <- apply(full_table3[, 2:8], 1, paste, collapse = ";")

full_acido3 <- full_table3 %>% 
  pivot_longer(names_to = "samples", values_to = "counts", 9:145)%>% 
  group_by(samples, Phylum, OTUID, ASV_FULL_tax) %>% 
  summarise(sum = sum(counts))%>% 
  filter(sum>0) #%>%
  #pivot_wider(names_from = "samples", values_from = "sum")

most_common_asv <- full_acido3 %>%
  group_by(Phylum) %>%
  count(ASV_FULL_tax) %>%
  top_n(1, n) %>%
  ungroup()

full_acido3 <- full_acido3 %>%
  inner_join(most_common_asv, by = c("Phylum", "ASV_FULL_tax"))

# Pivot wider to get the counts for each sample and calculate occurrence
full_acido3_wide <- full_acido3 %>%
  pivot_wider(names_from = "samples", values_from = "sum")

full_acido3_wide$occurrence <- rowSums(full_acido3_wide[5:140] > 0, na.rm = TRUE)

full_acido_pres5 <- full_acido3_wide %>%
  pivot_longer(names_to = "samples", values_to = "rel_abund", 5:140) %>%
  mutate(Site = "SJ")
```


```{r}
ggplot(full_acido_pres5, aes(y = ASV_FULL_tax, x= rel_abund, color = Site)) +
  stat_summary(fun.data = median_hilow, geom = "pointrange",
               fun.args = list(conf.int = .25),
               position = position_dodge(width = .5), size = .3) +
  scale_color_brewer(palette = "Set2") +
  labs(title = "Relative Abundance of Phyla by Site (SF Samples)",
       subtitle = "Median values with 50% confidence intervals",
       x = "Relative Abundance (%)", 
       y = "Phylum",
       color = "Taxonomic String") +
  theme(
    plot.title = element_text(size = 16, face = "bold", hjust = 0.5),
    plot.subtitle = element_text(size = 12, hjust = 0.5),
    axis.title.x = element_text(size = 12, face = "bold"),
    axis.title.y = element_text(size = 12, face = "bold"),
    axis.text.x = element_text(size = 10),
    axis.text.y = element_text(size = 10),
    legend.title = element_text(size = 12),
    legend.text = element_text(size = 10)
  )
```


```{r}
combo16S <- rbind(full_acido_pres1,full_acido_pres3,full_acido_pres5)
```


```{r}
combo_all <- combo16S %>% 
select(c("ASV_FULL_tax","Site")) %>% 
  unique()

combo_all1 <- combo16S %>% 
  filter(Phylum == "p__Acidobacteriota"|Phylum == "p__Actinobacteriota" | Phylum == "p__Bacteroidota" | Phylum == "p__Planctomycetota" | Phylum == "p__Proteobacteria" | Phylum == "p__Verrucomicrobiota"| Phylum ==
"	
p__WPS-2" | Phylum =="p__Chloroflexi" | Phylum == "
p__Myxococcota" | Phylum == "p__Methylomirabilota")

```


```{r}
ggplot(combo_all1, aes(y=Phylum,x=rel_abund, color=Site ))+
  stat_summary(fun.data = median_hilow, geom = "pointrange",
               fun.args = list(conf.int=.5),
               position = position_dodge(width=.5), size=.3)+
 # Customize color manually for the 'Site' variable
scale_color_brewer(palette = "Set2") +
  
  
  
  # Add titles, axis labels, and captions
  labs(title = "Relative Abundance of Phyla by Site for ALL Depths Combined",
       subtitle = "Median values with 50% confidence intervals",
       x = "Relative Abundance (%)", 
       y = "Phylum",
       color = "Sampling Site") +
  
  # Customize the axis and title text appearance
  theme(
    plot.title = element_text(size = 16, face = "bold", hjust = 0.5),
    plot.subtitle = element_text(size = 12, hjust = 0.5),
    axis.title.x = element_text(size = 12, face = "bold"),
    axis.title.y = element_text(size = 12, face = "bold"),
    axis.text.x = element_text(size = 10),
    axis.text.y = element_text(size = 10),
    
    # Customize legend appearance
    legend.title = element_text(size = 12),
    legend.text = element_text(size = 10)
  )
```

















Step 1: Pull out only the SF samples so that we can only look at those. 

```{r}
# otus <- read_csv("/Users/kyasparks/Desktop/16S_Maaslin_combined.csv")%>%
#   select(1,contains("_SF_"))

otus <- read_excel("/Users/kyasparks/Desktop/Kya's Phd/CSU 2023-2024/Projects/ASCC/ASCC_July2024_USETHIS_ks/16S/16S_Maaslin/ASCC_16S_feature_table_Maaslin_combo.xlsx", sheet = "ALL")%>%
  select(3,contains("_SF_"))
```

```{r}
taxa <- read.delim("/Users/kyasparks/Desktop/Kya's Phd/CSU 2023-2024/Projects/ASCC/ASCC_July2024_USETHIS_ks/16S/16S_taxonomy/filtered/ASCC_16S_taxonomy_forprocessing_copy.txt")



full_table <- inner_join(taxa, otus, by = "OTUID")
full_table$ASV_FULL_tax <- apply(full_table[, 2:8], 1, paste, collapse = ";")

full_acido1 <- full_table %>% 
  pivot_longer(names_to = "samples", values_to = "counts", 9:88)%>% 
  group_by(samples, Phylum, Domain, Class, Order, OTUID) %>% 
  summarise(sum = sum(counts))%>% 
  filter(sum>0) %>% 
  pivot_wider(names_from = "samples", values_from = "sum")


full_acido1$occurence <- rowSums(full_acido1[c(2:82)] > 0, na.rm=TRUE)

```

```{r}
full_acido_pres1 <- full_acido1 %>% 
  pivot_longer(names_to = "samples", values_to = "rel_abund", 6:86) %>% 
  mutate(Site = "SF")

full_acido_pres1$ASV_FULL_tax <- apply(full_acido_pres1[, 1:4], 1, paste, collapse = ";")
```


```{r}
ggplot(full_acido_pres1, aes(y=ASV_FULL_tax,x=rel_abund ))+
  stat_summary(fun.data = median_hilow, geom = "pointrange",
               fun.args = list(conf.int=.25),
               position = position_dodge(width=.5), size=.3)
```



```{r}
# otus <- read_csv("/Users/kyasparks/Desktop/16S_Maaslin_combined.csv")%>%
#   select(1,contains("_SF_"))

# otus <- read_excel("/Users/kyasparks/Desktop/Kya's Phd/CSU 2023-2024/Projects/ASCC/ASCC_July2024_USETHIS_ks/16S/16S_Maaslin/ASCC_16S_feature_table_Maaslin_combo.xlsx", sheet = "ALL")%>%
#   select(3,contains("_SF_"))
```

```{r}
# taxa <- read.delim("/Users/kyasparks/Desktop/Kya's Phd/CSU 2023-2024/Projects/ASCC/ASCC_July2024_USETHIS_ks/16S/16S_taxonomy/filtered/ASCC_16S_taxonomy_forprocessing_copy.txt")



# full_table <- inner_join(taxa, otus, by = "OTUID")
# full_table$ASV_FULL_tax <- apply(full_table[, 2:8], 1, paste, collapse = ";")

# full_acido1 <- full_table %>% 
#   pivot_longer(names_to = "samples", values_to = "counts", 9:88)%>% 
#   group_by(samples, Phylum, OTUID) %>% 
#   summarise(sum = sum(counts))%>% 
#   filter(sum>0) %>% 
#   pivot_wider(names_from = "samples", values_from = "sum")


# full_acido1$occurence <- rowSums(full_acido1[c(2:81)] > 0, na.rm=TRUE)

```

```{r}
# full_acido_pres1 <- full_acido1 %>% 
#   pivot_longer(names_to = "samples", values_to = "rel_abund", 2:81) %>% 
  # mutate(Site = "SF")
```


```{r}
# ggplot(full_acido_pres1, aes(y=Phylum,x=rel_abund ))+
#   stat_summary(fun.data = median_hilow, geom = "pointrange",
#                fun.args = list(conf.int=.25),
#                position = position_dodge(width=.5), size=.3)
```


```{r}
# otus2 <- read_csv("/Users/kyasparks/Desktop/16S_Maaslin_combined.csv")%>% 
#   select(1,contains("_TP_"))

otus2 <- read_excel("/Users/kyasparks/Desktop/Kya's Phd/CSU 2023-2024/Projects/ASCC/ASCC_July2024_USETHIS_ks/16S/16S_Maaslin/ASCC_16S_feature_table_Maaslin_combo.xlsx", sheet = "ALL")%>%
  select(3,contains("_TP_"))
```


```{r}
taxa <- read.delim("/Users/kyasparks/Desktop/Kya's Phd/CSU 2023-2024/Projects/ASCC/ASCC_July2024_USETHIS_ks/16S/16S_taxonomy/filtered/ASCC_16S_taxonomy_forprocessing_copy.txt")

full_table2 <- inner_join(taxa, otus2, by = "OTUID")

full_acido2 <- full_table2 %>% 
  #filter(Phyla == "  p__Acidobacteriota") %>% 
  pivot_longer(names_to = "samples", values_to = "counts",9:94)%>% 
  select(3,9:10) %>% 
  group_by(samples, Phylum) %>% 
  summarise(sum = sum(counts)) %>% 
  filter(sum>0) %>% 
  pivot_wider(names_from = "samples", values_from = "sum")


full_acido2$occurence <- rowSums(full_acido2[c(2:87)] > 0, na.rm=TRUE)

full_acido_pres3 <- full_acido2 %>% 
  pivot_longer(names_to = "samples", values_to = "rel_abund", 2:87) %>% 
  mutate(Site = "TP")

```


```{r}
ggplot(full_acido_pres3, aes(y=Phylum,x=rel_abund ))+
  stat_summary(fun.data = median_hilow, geom = "pointrange",
               fun.args = list(conf.int=.25),
               position = position_dodge(width=.5), size=.3)
```

```{r}
# otus3 <- read_csv("/Users/kyasparks/Desktop/16S_Maaslin_combined.csv")%>% 
#   select(1,contains("_SJ_"))

otus3 <- read_excel("/Users/kyasparks/Desktop/Kya's Phd/CSU 2023-2024/Projects/ASCC/ASCC_July2024_USETHIS_ks/16S/16S_Maaslin/ASCC_16S_feature_table_Maaslin_combo.xlsx", sheet = "ALL")%>%
  select(3,contains("_SJ_"))

```


```{r}
taxa <- read.delim("/Users/kyasparks/Desktop/Kya's Phd/CSU 2023-2024/Projects/ASCC/ASCC_July2024_USETHIS_ks/16S/16S_taxonomy/filtered/ASCC_16S_taxonomy_forprocessing_copy.txt")

full_table3 <- inner_join(taxa, otus3, by = "OTUID")

full_acido3 <- full_table3 %>% 
  #filter(Phyla == "  p__Acidobacteriota") %>% 
  pivot_longer(names_to = "samples", values_to = "counts",9:145)%>% 
  select(3, 9:10) %>% 
  group_by(samples, Phylum) %>% 
  summarise(sum = sum(counts)) %>% 
  filter(sum>0) %>% 
  pivot_wider(names_from = "samples", values_from = "sum")


full_acido3$occurence <- rowSums(full_acido3[c(2:137)] > 0, na.rm=TRUE)

full_acido_pres5 <- full_acido3 %>% 
  pivot_longer(names_to = "samples", values_to = "rel_abund", 2:137) %>% 
  mutate(Site = "SJ")

```


```{r}
ggplot(full_acido_pres5, aes(y=Phylum,x=rel_abund ))+
  stat_summary(fun.data = median_hilow, geom = "pointrange",
               fun.args = list(conf.int=.25),
               position = position_dodge(width=.5), size=.3)
```


```{r}
combo16S <- rbind(full_acido_pres1,full_acido_pres3,full_acido_pres5)
```


```{r}
combo_all <- combo16S %>% 
select(c("Phylum","Site")) %>% 
  unique()

combo_all1 <- combo16S %>% 
  filter(Phylum == "p__Acidobacteriota"|Phylum == "p__Actinobacteriota" | Phylum == "p__Bacteroidota" | Phylum == "p__Planctomycetota" | Phylum == "p__Proteobacteria" | Phylum == "p__Verrucomicrobiota"| Phylum ==
"	
p__WPS-2" | Phylum =="p__Chloroflexi" | Phylum == "
p__Myxococcota" | Phylum == "p__Methylomirabilota")

```


```{r}
ggplot(combo_all1, aes(y=Phylum,x=rel_abund, color=Site ))+
  stat_summary(fun.data = median_hilow, geom = "pointrange",
               fun.args = list(conf.int=.5),
               position = position_dodge(width=.5), size=.3)+
 # Customize color manually for the 'Site' variable
scale_color_brewer(palette = "Set2") +
  
  
  
  # Add titles, axis labels, and captions
  labs(title = "Relative Abundance of Phyla by Site for ALL Depths Combined",
       subtitle = "Median values with 50% confidence intervals",
       x = "Relative Abundance (%)", 
       y = "Phylum",
       color = "Sampling Site") +
  
  # Customize the axis and title text appearance
  theme(
    plot.title = element_text(size = 16, face = "bold", hjust = 0.5),
    plot.subtitle = element_text(size = 12, hjust = 0.5),
    axis.title.x = element_text(size = 12, face = "bold"),
    axis.title.y = element_text(size = 12, face = "bold"),
    axis.text.x = element_text(size = 10),
    axis.text.y = element_text(size = 10),
    
    # Customize legend appearance
    legend.title = element_text(size = 12),
    legend.text = element_text(size = 10)
  )
```

